# Output path for training runs. Each training run makes a new directory in here.
output_dir = 'output'

# Dataset config file.
dataset = 'dataset.toml'
# You can have separate eval datasets. Give them a name for Tensorboard metrics.
# eval_datasets = [
#     {name = 'infernus_eval', config = '/mnt/tsar/diffusion-pipe/datasets/1_eval.toml'},
# ]

# training settings

# I usually set this to a really high value because I don't know how long I want to train.
epochs = 100
# Batch size of a single forward/backward pass for one GPU.
micro_batch_size_per_gpu = 3
# Pipeline parallelism degree. A single instance of the model is divided across this many GPUs.
pipeline_stages = 1
# Number of micro-batches sent through the pipeline for each training step.
# If pipeline_stages > 1, a higher GAS means better GPU utilization due to smaller pipeline bubbles (where GPUs aren't overlapping computation).
gradient_accumulation_steps = 1
# Grad norm clipping.
gradient_clipping = 0.0
# Learning rate warmup.
warmup_steps = 5

# Block swapping is supported for Wan, HunyuanVideo, Flux, and Chroma. This value controls the number
# of blocks kept offloaded to RAM. Increasing it lowers VRAM use, but has a performance penalty. The
# exactly performance penalty depends on the model and the type of training you are doing (e.g. images vs video).
# Block swapping only works for LoRA training, and requires pipeline_stages=1.
blocks_to_swap = 18

# eval settings

eval_every_n_epochs = 1
eval_before_first_step = true
# Might want to set these lower for eval so that less images get dropped (eval dataset size is usually much smaller than training set).
# Each size bucket of images/videos is rounded down to the nearest multiple of the global batch size, so higher global batch size means
# more dropped images. Usually doesn't matter for training but the eval set is much smaller so it can matter.
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1

# misc settings

# Probably want to set this a bit higher if you have a smaller dataset so you don't end up with a million saved models.
save_every_n_epochs = 1
# Can checkpoint the training state every n number of epochs or minutes. Set only one of these. You can resume from checkpoints using the --resume_from_checkpoint flag.
#checkpoint_every_n_epochs = 1
checkpoint_every_n_minutes = 60
# Always set to true unless you have a huge amount of VRAM.
activation_checkpointing = 'unsloth'
# Controls how Deepspeed decides how to divide layers across GPUs. Probably don't change this.
partition_method = 'parameters'
# dtype for saving the LoRA or model, if different from training dtype
save_dtype = 'bfloat16'
# Batch size for caching latents and text embeddings. Increasing can lead to higher GPU utilization during caching phase but uses more memory.
caching_batch_size = 1
# How often deepspeed logs to console.
steps_per_print = 1

# --- Inference configuration ---
[inference]
# Generate samples every N epochs (set > 0 to enable)
inference_every_n_epochs = 5
# Or generate every N steps (set one, or both if needed)
# inference_every_n_steps = 500
# Folder where samples will be saved (relative to the run directory)
inference_folder = "samples"
# Number of denoising steps
steps = 20
# Guidance scale (Chroma specific, might be 0)
guidance = 0
# Classifier-free guidance scale
cfg = 3
# First N steps without classifier-free guidance
first_n_steps_wo_cfg = 0
# Image dimensions [width, height] - MATCH YOUR TRAINING DATA/MODEL EXPECTATIONS
image_dim = [512, 512]
# Maximum length for T5 tokenizer
t5_max_length = 512
# Prompts for sample generation
prompts = [
    "a cute cat sat on a mat while receiving a head pat from his owner called Matt",
    "baked potato, on the space floating orbiting around the earth"
]
# Optional seed for reproducible samples (otherwise uses rank+step)
seed = 42

[model]
type = 'chroma'
transformer_path = '/workspace/models/chroma/chroma-unlocked-v32.safetensors'
diffusers_path = '/workspace/models/flux'
# Base dtype used for all models.
dtype = 'bfloat16'
transformer_dtype = 'float8'
# Enable flux_shift for dynamic position scaling - critical for sampling at different resolutions
flux_shift = true

# For models that support full fine tuning, simply delete or comment out the [adapter] table to FFT.
[adapter]
type = 'lora'
rank = 16 # Increase rank if needed
dtype = 'bfloat16'
dropout = 0.2 # Adjust dropout

# --------------------------------
# OPTIMIZER CONFIGURATIONS
# --------------------------------
# Uncomment one of the configurations below and comment out the others

# --------- AUTOMAGIC OPTIMIZER ---------
# Automagic optimizer - Adaptive learning rate optimizer with per-parameter learning rates
# [optimizer]
# type = 'automagic'
# lr = 1e-6  # Start learning rate (will be clamped to max 1e-3)
# min_lr = 1e-7  # Minimum learning rate
# max_lr = 1e-3  # Maximum learning rate
# lr_bump = 1e-6  # Amount to bump the lr when adjusting
# beta2 = 0.999  # Beta2 parameter for exponential moving average
# weight_decay = 0.0  # Weight decay
# clip_threshold = 1.0  # Gradient clipping threshold

# --------- DEFAULT OPTIMIZER ---------
# SCORN optimizer -  Default configuration 
[optimizer]
type = 'scorn'  
lr = 1e-4
weight_decay = 0.01


# REMASTER optimizer - Alternative configuration
# [optimizer]
# type = 'remaster'  
# lr = 1e-4
# weight_decay = 0.01
# orthograd = true
# amp = 5.0
# stochastic_fp = true


# PersonaOptimizer - Feature-focused learning configuration
# [optimizer]
# type = 'persona'
# lr = 1e-4
# weight_decay = 0.01
# focus_boost = 0.05  # Enables gradient variance modulation (0.0 to disable)
# amp_factor = 1.0
# orthograd = false
# stochastic_fp = true


# --------- MEMORY-OPTIMIZED OPTIMIZERS ---------
# Adafactor optimizer - Default configuration (memory efficient)
# [optimizer]
# type = 'adafactor'
# lr = 1e-4
# scale_parameter = false
# relative_step = false
# weight_decay = 0.01

# Prodigy optimizer
# [optimizer]
# type = "Prodigy"
# weight_decay = 0.05

# AdamW8bitKahan optimizer - Memory efficient
# [optimizer]
# type = 'AdamW8bitKahan'
# lr = 2e-5
# weight_decay = 0.01